### ISSUE TITLE
Version 2.3 checklist

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#184]
- [x] Wait for #161 
- [x] Add the rest of the missing changelog entries (as tagged in the PRs)
- [x] Update README with the new features
- [x] Mention the 3.6/3.7 version in the readme
- [x] Make the current version a little more obvious in the docs.
- [x] Add PyPI links
- [x] Move to using `main`
- [x] investigate kw dicts
